name: docker hub
on: 
 push:
  branches:
   - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
    - name: checkout code
      uses: actions/checkout@v4
    - name: set up docker
      uses: docker/setup-buildx-action@v2
    - name: login to docker
      uses: docker/login-action@v2
      with: 
        USERNAME: ${{ docker_username }}
        PASSWORD: ${{ docker_password }}

    - name: build and push image
      run: |
       docker build -t my-image:latest
       docker push my-image:latest
       
  
